name: Bug Report
description: Report a bug or unexpected behavior
labels: [bug, triage]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the form below.

  - type: checkboxes
    id: existing-issue
    attributes:
      label: Prerequisites
      description: Please confirm before submitting
      options:
        - label: I have searched existing issues to ensure this bug has not already been reported
          required: true

  - type: input
    id: version
    attributes:
      label: iCalDAV Version
      description: Which version of iCalDAV are you using?
      placeholder: e.g., 1.0.0
    validations:
      required: true

  - type: dropdown
    id: module
    attributes:
      label: Affected Module
      description: Which module is affected?
      options:
        - icalendar-core
        - webdav-core
        - caldav-core
        - caldav-sync
        - ics-subscription
        - caldav-android
        - Multiple / Unknown
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Create event with...
        2. Call parser.parse()...
        3. See error...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
    validations:
      required: true

  - type: textarea
    id: ics-sample
    attributes:
      label: ICS Sample (if applicable)
      description: |
        If the bug involves ICS parsing, please provide a minimal ICS sample.
        **Remove any personal information before sharing.**
      render: text
      placeholder: |
        BEGIN:VCALENDAR
        VERSION:2.0
        ...
        END:VCALENDAR

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Please provide environment details
      placeholder: |
        - JDK version: 17
        - OS: Ubuntu 22.04
        - Android version (if applicable): 14
        - CalDAV server (if applicable): Nextcloud
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Error Logs / Stack Trace
      description: If applicable, paste relevant error logs or stack traces
      render: shell

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context about the problem